version: 1.0.{build}
os: Visual Studio 2017
configuration: Release

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore
  
build:
 verbosity: minimal

test_script:
  - cd tests\Useful.Extensions.Tests
  - dotnet xunit
